version: '3.8'

services:
  # pytest:
  #   build: .
  #   command: pytest 
  #   volumes:
  #     - ./logs:/app/logs:rw  
  #     - ./reports:/app/reports:rw 
  appserver:
    build: ./app
    ports:
      - "8081:8080"
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    command: python3 -u app.py
    


  

    